name: flutter_horizontal_featured_list
description: A Flutter package to create Horizontal Featured List. It helps you in saving time during the development of many same designs.
version: 1.0.0
homepage: https://minhhung2556.github.io
repository: https://github.com/minhhung2556/romantic_project_flutter_horizontal_featured_list.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: