name: flutter_horizontal_featured_list
description: A Flutter package to create Rating Stars bar. It will be useful for your awesome app.
version: 1.0.3+1
homepage: https://minhhung2556.github.io
repository: https://gitlab.com/romantic_project/flutter_horizontal_category_list

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: